[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."process-pdf"]
  timeout = 60

[functions."add-booking"]
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
